name: "🐛 Bug Report"
description: "Report a bug or issue with the Kasbah Learn Hub Frontend"
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛
        
        Please fill out this form to help us understand and fix the issue quickly.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have checked the documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste URLs

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Low (Minor inconvenience)"
        - "Medium (Affects functionality)"
        - "High (Blocks major functionality)"
        - "Critical (App crash/data loss)"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g. Chrome 119.0.0.0
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g. Windows 11, macOS 14.1, iOS 17.1
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution
      description: What's your screen resolution?
      placeholder: e.g. 1920x1080, 1366x768

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any console errors or warnings? (Press F12 → Console)
      placeholder: Paste any console errors here...
      render: shell

  - type: textarea
    id: network-errors
    attributes:
      label: Network Errors
      description: Any network errors in the Network tab?
      placeholder: Paste any network errors here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - User account type (student/instructor/admin)
        - Specific course or content involved
        - Time of occurrence
        - Any recent changes made

  - type: checkboxes
    id: testing
    attributes:
      label: Testing
      description: Have you tested this in different scenarios?
      options:
        - label: Tested in incognito/private mode
        - label: Tested with different user accounts
        - label: Tested on different devices
        - label: Tested with disabled extensions/plugins

  - type: markdown
    attributes:
      value: |
        ---
        
        **For Developers:**
        - Add relevant labels after triage
        - Assign to appropriate team member
        - Link to related issues if applicable
        
        Thank you for helping make Kasbah Learn Hub better! 🚀